# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_auto_20170710_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
