# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_sourceurl_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='final.SourceTag'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
